version: "3.8"

services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./proxy/index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - auth
      - order
      - api
      - profile
      - delivery

  auth:
    image: traefik/whoami:latest
  

  order:
    image: traefik/whoami:latest

  api:
    image: traefik/whoami:latest
  
  profile:
    image: traefik/whoami:latest

  delivery:
    image: traefik/whoami:latest
    


