user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log notice;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream auth_service {
        server auth;
    }

    upstream order_service {
        server order;
    }

    upstream api_service {
        server api:80;
    }
    upstream profile_service {
        server profile;
    }
    upstream delivery_service {
        server delivery;
    }
    


    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /auth/ {
            proxy_pass http://auth_service/;
        }

        location /order/ {
            proxy_pass http://order_service/;
        }

        location /api/ {
            proxy_pass http://api_service/;
        }

        location /profile/ {
            proxy_pass http://profile_service/;
        }

        location /delivery/ {
            proxy_pass http://delivery_service/;
        }
    }
}