name: Docker Compose CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-compose:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.1.0

      - name: Validate Compose
        run: docker compose config

      - name: Start Services
        run: docker compose up -d

      - name: Show Containers
        run: docker compose ps

      - name: Test Auth Service
        run: curl http://localhost/auth

      - name: Test Order Service
        run: curl http://localhost/order

      - name: Test API Service
        run: curl http://localhost/api

      - name: Test Profile Service
        run: curl http://localhost/profile

      - name: Test Delivery Service
        run: curl http://localhost/delivery

      - name: Stop Services
        if: always()
        run: docker compose down
        